### ISSUE TITLE
Mono Query: Add time interval to query parameter

### ISSUE THREAD

**Issue by marxprop** [Acceede-HQ/Credit-ML#1]
Ensure the mono request in MLModel.py adds the time interval parameter in the request query for the last 12months.
Docs: https://docs.mono.co/api/bank-data/transactions.

**Comment by Platayo** [comment]
I pushed the code for your review

**Comment by marxprop** [comment]
@Platayo , Please open another PR for this issue, 
Ensure that start_date and end_date are in parentheses.

Url:   https://github.com/Acceede-HQ/Credit-ML/pull/2#discussion_r1534195837

**Comment by Platayo** [comment]
All done man
