### ISSUE TITLE
Find reoccuring payments

### ISSUE THREAD

**Issue by marxprop** [Acceede-HQ/Credit-ML#6]
Requirements:
We need to able to be able to discover the top reoccuring incoming payments from a user's transaction over the year. These transactions can either be weekly, biweekly or monthly.

Expected results: Return a list with each item containing a list of reoccuring payments in the same category
```python
 incomes = [
             [List of all the rows of the reoccuring transactions with the highest amount], 
             [List of all the rows of the reoccuring transactions with the second highest amount],
             [List of all the rows of the reoccuring transactions with the third highest amount],
             ..............
           ]
```

Other requirements.
- Create a new file in the analysis folder that handles analysis like this.
- Create a new function called `get_incomes` that accepts a pandas dataframe and returns the expected list.
- Add pydantic typing to your functions if necessary.
- Make sure to use numpy or pandas inbuilt stat methods for quick computations.
- The returned results from above can also be a numpy array or list of dataframes

**Comment by Platayo** [comment]
Alright boss.

**Comment by Platayo** [comment]
def get_income(data):
    recurring_amount_list = []
    credit_rows = data['type'] == 'credit'
    credit_transactions = data[credit_rows]

    for _, rows in credit_transactions.iterrows():
        # group credit transactions by category and amount, then count occurence
        credits_by_cat_amount = credit_transactions.groupby(['category', 'amount']).size().reset_index(name='count')

        # sort categories by count in descending order 
        sorted_cat_amount = credits_by_cat_amount.sort_values(by='count', ascending = False)

        # top 3 category and amount
        top_cat_amount = sorted_cat_amount.head(3)

    recurring_amount_list.append(top_cat_amount)

    return recurring_amount_list

**Comment by Platayo** [comment]
[             category  amount  count
 28  personal_transfer  5000.0     19
 56     returned_debit  5000.0     10
 21  personal_transfer  2000.0      8]
 
 That is a sample of the code output

**Comment by marxprop** [comment]
Hi @Platayo , I cant find your pull request

**Comment by marxprop** [comment]
> I am having problems pushing the code, so I just pasted it here. Please I need your review

Okay, I see... 
- Ensure your local main branch is in sync with what we have here on github. Use `git pull`
- Create a new branch from that main branch.
- Make your changes to the new branch, push to the new branch and create a new PR
